
name: Build and deploy container app to Azure Web App - demolingwinguser

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_6d3b2f66ac39446aa0995485973e8964 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b04ac67724e94c62bb3f783e78a29019 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6d3b2f66ac39446aa0995485973e8964 }}/soundma/lingwinguser:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'demolingwinguser'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_684cbac4e8124901b2017e50dec55da0 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6d3b2f66ac39446aa0995485973e8964 }}/soundma/lingwinguser:${{ github.sha }}'
